### ISSUE TITLE
Latest version (1.3.1) not present on Maven repositories

### ISSUE THREAD

**Issue by vader2000** [wywygmbh/log4j-plugin-fluency#4]
According to
https://mvnrepository.com/artifact/com.wywy/log4j-plugin-fluency
and
https://bintray.com/bintray/jcenter/com.wywy%3Alog4j-plugin-fluency#
latest release is not present there.

**Comment by lobeck** [comment]
I'm really sorry for this and the delay :(

1.3.1 was just published there too.
